# Generated by Django 4.1.5 on 2024-06-21 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vdpurls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FtpConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("single", "single"), ("batch", "batch")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("parse_xml_edealer", "parse_xml_edealer"),
                            ("parse_csv", "parse_csv"),
                            ("parse_csv_insert_dname", "parse_csv_insert_dname"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "feed_ids",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Feed Ids (comma-separted list values)",
                    ),
                ),
                (
                    "target_fields",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Target Fields (comma-separted list values)",
                    ),
                ),
                ("ftp_host", models.CharField(max_length=50, null=True)),
                ("ftp_user", models.CharField(max_length=50, null=True)),
                ("ftp_pass", models.CharField(max_length=50, null=True)),
                ("ftp_port", models.IntegerField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider",
                        to="vdpurls.webprovider",
                    ),
                ),
            ],
        ),
    ]
