# Generated by Django 4.1.5 on 2024-06-26 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vdpurls", "0002_ftpconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ftpconfig",
            options={"ordering": ("provider",)},
        ),
        migrations.RenameField(
            model_name="dealer",
            old_name="account",
            new_name="account_status",
        ),
        migrations.AlterField(
            model_name="ftpconfig",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webprovider",
                to="vdpurls.webprovider",
            ),
        ),
    ]
